### ISSUE TITLE
ZincObserve ingestion duration，Refresh the page to become a blank

### ISSUE THREAD

**Issue by e8tg001** [zinclabs/zincobserve#484]
### Which ZincObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

I use the "Vector" upload 472MB of nginx logs, the CPU usage is too high and the UI page refresh becomes blank; please evaluate whether there is performance and usage impact during large-scale log collection;
![image](https://user-images.githubusercontent.com/40289299/229277764-eb5e23d9-b52c-4065-92a9-63872eecd768.png)
![image](https://user-images.githubusercontent.com/40289299/229277786-a062decf-132f-437f-9877-832020d6dd57.png)
![image](https://user-images.githubusercontent.com/40289299/229277791-ebcfee93-5949-4ef3-ad75-6d05a5809b28.png)
![image](https://user-images.githubusercontent.com/40289299/229277800-4e4e5bbd-eb74-48b1-a175-4f1bdfe7e0ce.png)

### Please provide the exception or error you saw

```true
repeated emergence
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
version:0.3.1
sha1sum:8ade56d4da0ac28981eb32e5fbe75a8214a68ba3
Linux centos72.9377 3.10.0-957.21.3.el7.x86_64   
8*CPU  
16G
```

**Comment by prabhatsharma** [comment]
You essentially overwhelmed ZO. 472 MB of data if sent quickly on a single node can be a lot. You can make things easier on ZO by configuring vector using the combination of the following settings:


```toml
[sinks.my-sink]
  request.concurrency = 10
  request.concurrency = "adaptive" # use this or the above line
  request.rate_limit_duration_secs = 1
  request.rate_limit_num = 10

```

You can find more info at https://vector.dev/docs/reference/configuration/sinks/vector/#rate-limits
