### ISSUE TITLE
can not run in linux and docker-compose with empty image[Missing dependent module in linux]

### ISSUE THREAD

**Issue by z284949127** [zinclabs/zincobserve#567]
### Which ZincObserve functionalities are relevant/related to the feature request?

other

### Description

* when i run on my diskstation DSM 7+ in shell, it gose out errors:
  * ```./zincobserve: /lib/libm.so.6: version `GLIBC_2.27' not found (required by ./zincobserve)```

* my start sh file:
```shell
ZO_ROOT_USER_EMAIL=root@qq.com
ZO_ROOT_USER_PASSWORD=123456
./zincobserve
```
-----------
* and when i run on docker-compose with empty image:cfgarden/empty:latest, it gose out errors too!:
  * ```dc_zinc_observer | standard_init_linux.go:230: exec user process caused: no such file or directory```

* my docker-compose.yml file:
```yml
# docker compose部署java
#
# @author zhongbo
# @homepage http://7mo.org
# @date 2022-10-8 00:52:03
# @see <a href="https://blog.csdn.net/Aria_Miazzy/article/details/89326829">docker-compose.yml配置文件详解</a>

version: '3'                                    # 指定版本名(已过期)
services: # 配置服务列表(顶级元素)
  firstService: # 服务名称(随便取,当前文件中不重名即可)
    image: cfgarden/empty:latest                    # 指定镜像和版本  (docker仓库的镜像名称和版本)
    container_name: dc_zinc_observer                  # 指定容器名称
    volumes: # 卷配置
      - ./:/work/app/                           # 卷冒号用法 [外部路径]:[内部路径]
    ports: # 端口映射配置
      - "5080:5080"                             # 指定容器端口映射[对外端口]:[内部端口]
    restart: always                             # 重启策略
    # 容器内工作目录
    working_dir: /work/app/
    # <a href="https://blog.csdn.net/qq_37768368/article/details/120583141">docker-compose.yml详解[带全部命令]</a>
    # 覆盖容器的默认 entrypoint 指令 (等同于 docker run --entrypoint 的作用)
    # 指定启动命令
    entrypoint: ./zincobserve
    # <a href="https://blog.csdn.net/weixin_43788143/article/details/120017270">docker-compose.yml中environment的参数详情（以zookeeper集群为例）</a>
    # 配置docker container的环境变量
    environment:
      ZO_ROOT_USER_EMAIL: root@qq.com
      ZO_ROOT_USER_PASSWORD: 123456
```
----------
* **★★★always last! I really wants your binary file with out any dependences, either you choosed go lang to write it!★★★**
* (This upon line is the  point!!!) and I can't start up zincobserver in my docker in linux system DSM7+
----------

### Proposed solution

1. support no dependence glibc, etc. for binary file make;
2. tell me how to make it run as a docker-compose file with a basic docker image;
3. don't don't has dependences! 
4. Never use a dependency module, otherwise I really won't be able to run it ToT;

### Alternatives considered

1. give me a docker-compose.yml file, that I can run the file "zincobserve"
2. help me to run 'zincobserver' file in a diskstation docker envirement
* my docker version:
```
Docker version 20.10.3, build b35e731
docker-compose version 1.28.5, build 1bbbad71
docker base image: cfgarden/empty:latest
```
